### ISSUE TITLE
[Feature] Render the stored HTML in the UI

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-frontend#10]
## Issue

While the Google search result content is stored in the database, users can only view the HTML as code. The page is not viewable.

https://github.com/Prabeshpd/web-scraper-frontend/blob/14645f7abe38db98c4eeb97645b97c711cda2c77/src/components/searchPage/SearchDetail.tsx#L45-L52

As a result, a user cannot verify if the scraping results are correct.

## Expected

The HTML content should be viewable on the application, e.g., there could be a view of the content on a new page or in a modal.

> **Note**
> There is a bit of a challenge to render HTML content from another page. Hence it is an expected feature of the application.

**Comment by Prabeshpd** [comment]
I agree with you here certainly. I have added render feature to render the raw html load saved from scraping the database. Used Modal to load the html.

For now used the package html-react-parser to parse string to react element as it would take some time to build a custom util function to convert to htmlElement and parse them to create react element.

**Comment by olivierobert** [comment]
To display the content of the HTML content of another page, another simpler solution would be to use an iframe. In this case, the `srcdoc` attribute can be used to inject the HTML content to the iframe: https://www.w3schools.com/tags/att_iframe_srcdoc.asp
