### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-frontend#7]
Hello Prabesh 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
@Prabeshpd I have completed the first review round of code reviews and would like your feedback on the open issues. Please check the other repositories. 

Since this submission has many components, it would be best to provide a Docker-based or equivalent to ensure all dependencies can be set up (Postgres, RabbitMQ, and Redis)

**Comment by Prabeshpd** [comment]
@olivierobert 

Thank you for your response and first round of code review. I will
certainly go through the comments and reply back to you. I was thinking of
making a docker-compose file to run the project. I was on a tight deadline
as I was busy completing my regular office duties as well so could not make
a docker file.
 I will commit it and go through the other issues as well.

**Comment by Prabeshpd** [comment]
I have addressed the issues. Can you please go through them? @olivierobert

**Comment by olivierobert** [comment]
I have reviewed the changes 👍 I would need you to review and provide at least some feedback to the open issues on this repository 😅 It would be great if we can wrap up the code review today or tomorrow at the latest.

**Comment by Prabeshpd** [comment]
@olivierobert  I have created PR and merge them for most of the issues mentioned. I have replied on the latest comment as well. Can you take a look at it?

**Comment by olivierobert** [comment]
I have now completed the review of all open issues. It is thus time to wrap up the code review. We appreciate your efforts during this process. Our team will contact you shortly.
