### ISSUE TITLE
[Question] Why not setting up the project as a mono-repository?

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-frontend#8]
## Issue

The project contains four different repositories, thus requiring to start four applications simultaneously. While separation of responsibilities is a good idea, a standard practice in the Node.JS community is split the project into separate packages and having them in one mono-repository. There are numerous open source solutions to manage such structure such as [Lerna](https://lerna.js.org/) and [Turbo](https://turbo.build/repo/docs/handbook/what-is-a-monorepo). So I am curious why not opting for this route.

> **Note**
> There is currently a lot of code duplication (e.g., Knex configuration, helpers functions such as `camelize`) that could have been shared in a "common" package under the same repository for instance.

**Comment by Prabeshpd** [comment]
@olivierobert 
First thought was to create separate repo for only the frontend and backend. As I was segregating the repository my initial thought was there must be a separation of concern for each process. Thought here was that each process can be deployed separately in a `ECS` instance or such services. This would enable to scale the service independently. Looking at this now, I also believe that placing all these under single repository would have been easier to manage. Regarding the deployment and CI/CD pipelines we could have easily manage through the folders of each service.
The thought process was also that each team of developer would contribute to each service on the long run which would help the release of one service to another service independently. It was a bit farfetched plan.

Regarding the duplication of code. I was planning to have all the codes that can be shared to be placed in a separate folder and publish them as `npm` package and use it. As you mentioned there are duplication in helpers function, knex configuration and database function. As, I was running low on time, I went with the quick solutions here. If I had to look from deployment standpoint then I would definitely place the different repository as mono-repository and have a separate package of most used functions that can be shared.
